# Learning numpy

In [1]:
import numpy as np

In [2]:
myarr=np.array([9,10,4,5])

In [3]:
print(myarr)

[ 9 10  4  5]


In [4]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


# range

In [5]:
for i in myarr:
    print(i)

9
10
4
5


In [6]:
for i in range(0,21):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [7]:
arr2 = np.arange(0,21)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
list2 = [i for i in range(0,21)]
print(list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


# random

In [9]:
# rand  - generate between 0 and 1
# randn - generate close to 0
# randint - genrate integer value

In [10]:
array_rand = np.random.rand(3)
print(array_rand)

[0.56237509 0.46499374 0.73639429]


In [11]:
array_rand = np.random.rand(3,3)
print(array_rand)

[[0.72789304 0.34126659 0.52477621]
 [0.7645654  0.20036641 0.3984935 ]
 [0.69498187 0.49814284 0.47194248]]


In [12]:
array_randn=np.random.randn(5)
print(array_randn)

[-1.61479047 -0.54799078  2.10346473 -0.93983675  0.17117167]


In [13]:
array_randn=np.random.randn(5,4)
print(array_randn)

[[ 0.4757908  -2.21917612  0.40300887 -1.43049549]
 [ 0.62698784  0.79054168  0.20495711  0.93732097]
 [ 0.54182436  1.19309644  1.96991347  0.96438378]
 [ 0.05123352 -0.12538347  1.22011689  1.8298009 ]
 [ 1.0571198  -1.15272889 -0.25542    -1.437764  ]]


In [14]:
array_randint=np.random.randint(0,20,size=5) #(start,stop,size)
print(array_randint)

[ 3 19 10  0  7]


In [15]:
array_randint=np.random.randint(0,20,size=(5,10)) #(start,stop,size)
print(array_randint)

[[ 4 16  7  1 13  7  8 14  7  4]
 [14 12 14 19 18  7 16  7  5 12]
 [ 7 14  0  2 14  9 11  1  6 11]
 [ 0 15  6  5  0  1 16  3  5  1]
 [10  2 10 17 17 15  9 11  8 19]]


In [16]:
print("hello")

hello


# Dimension in array

In [17]:
array1=np.array([1,2,3,4,5,6])
#to check the dimension in array
#we use ndim function
print(array1.ndim)

1


In [18]:
array2=np.array([[1,2,3,4],[5,6,7,8]])
#check the dimension of this array
print(array2.ndim)

2


In [19]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3.ndim)

3


# To make the array dimension by desire

In [20]:
#ndmin
array_d= np.array([1,2,3,4],ndmin=2) #two dimensional array banaucha ndmin=2 garda
print(array_d)

[[1 2 3 4]]


In [21]:
#create 10 dimensional array
array_d=np.array([1,2,3,4,5],ndmin=10)
print(array_d)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


# Some functions in numpy

In [22]:
#zeros
#ones
#identity
zero_arr=np.zeros(3)
print(zero_arr)

[0. 0. 0.]


In [23]:
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
array_identity=np.identity(4)
print(array_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
# Two dimesional zero of size 2 rows and 2 column 
array_zero=np.zeros((2,2))
print(array_zero)

[[0. 0.]
 [0. 0.]]


In [26]:
#5 rows and 6 colunms of one
array_ones=np.ones((5,6))
print(array_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [27]:
# identity matrix
#eye
array_identity=np.eye(10)
print(array_identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Arithmatic operation in numpy


In [28]:
array_1=np.array([1,2,3,4])
#perform addition operation with 5
array_1 + 5


array([6, 7, 8, 9])

In [29]:
#create two array and perform
#addition,substraction,multiplication and division

array1=np.array([1,2,3,4])
array2=np.array([3,4,5,6])
# print("Addition of array1 and array2 is:",array1+array2)
print(f"Addition of array1 and array2 is:{array1+array2}")
# print("substraction of array1 and array2 is:",array1-array2)
# print("multiplication of array1 and array2 is:",array1*array2)
# print("division of array1 and array2 is:",array1/array2)




Addition of array1 and array2 is:[ 4  6  8 10]


In [30]:
#First generate the 2 dimensional array using randint and perform all four operation
array=np.random.randint(1,10,  size=(3,3))
array1=np.random.randint(1,10, size=(3,3))

print(array)
print(array1)
print(f"addition:{array+array1}")
print(f"substraction:{array-array1}")
print(f"multiplication:{array*array1}")
print(f"divison:{array/array1}")

[[4 9 3]
 [6 6 3]
 [9 7 1]]
[[9 3 3]
 [5 6 8]
 [1 1 1]]
addition:[[13 12  6]
 [11 12 11]
 [10  8  2]]
substraction:[[-5  6  0]
 [ 1  0 -5]
 [ 8  6  0]]
multiplication:[[36 27  9]
 [30 36 24]
 [ 9  7  1]]
divison:[[0.44444444 3.         1.        ]
 [1.2        1.         0.375     ]
 [9.         7.         1.        ]]


# Slicing operation in

In [31]:
#arrayname[start_value:stop_value:step]
arr1=np.arange(10)
print(arr1[5:8])

[5 6 7]


In [32]:
# 0 to 20
array1=np.arange(20)
# print(array1[0:20:2])
# print(array1[::2])

In [33]:
#slicing in 2d array
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
print(array_2d[0:1,1:3])

[[2 3]]


In [35]:
array_2d=np.array([[9,8,7,6],[23,45,67,78]])
print(array_2d)
print(array_2d[1:2,1:3])

[[ 9  8  7  6]
 [23 45 67 78]]
[[45 67]]


In [36]:
array_2d1=np.array([[5,6,7,8],[3,4,5,6],[11,12,34,43]])
print(array_2d1)
print(array_2d1[1:3,0:2])

[[ 5  6  7  8]
 [ 3  4  5  6]
 [11 12 34 43]]
[[ 3  4]
 [11 12]]


# Shaping and reshaping in numpy array

In [37]:
array_2d=np.array([1,2,3,4,5])
array_2d.shape

(5,)

In [38]:
array_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array_2d.shape) #rows and column print garcha

(3, 4)


In [39]:
#reshape is numpy array


In [40]:
array=np.array([1,2,3,4])
array.reshape(2,2) #kati ota cha teti ota halim jasto 2,2

array([[1, 2],
       [3, 4]])

In [42]:
#create the array of 12 element using arange function and reshape the array in 4 by 3
arr=np.arange(12)
print(arr)
print()
print(arr.reshape(3,4))
print(arr.reshape(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
mat1=np.matrix([1,2,3])
print(type(mat1))

<class 'numpy.matrix'>


In [51]:
mat1=np.matrix([[1,2],[4,5]])
mat2=np.matrix([[1,2],[4,5]])
print(type(mat1))
#create two 2d matrix and perform multiply operation 
print(f"multiplication:{mat1*mat2}")

<class 'numpy.matrix'>
multiplication:[[ 9 12]
 [24 33]]
