# Learning Numpy at home

In [1]:
import numpy as np

In [2]:
myarr=np.array([1,2,3,4,5,6])
print(myarr)

[1 2 3 4 5 6]


In [3]:
print(type(myarr))

<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

2.3.2


In [5]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# Create a 0-D array with value 42

In [6]:
arr=np.array(42)
print(arr)

42


# Create a 1-D array containing the values 1,2,3,4,5:

In [7]:
arr=np.array([1,2,3,45,566,7])
print(arr)

[  1   2   3  45 566   7]


# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [8]:
my2darr=np.array([[1,2,3],[4,5,6]])
print(my2darr)

[[1 2 3]
 [4 5 6]]


# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [9]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Check Number of Dimensions? 

In [10]:
#ndim attribute 
a=np.array(42)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


# Create an array with 5 dimensions and verify that it has 5 dimensions:

In [11]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

In [12]:
arr=np.array([1,2,3,4,5])
print(arr[2])

3


In [13]:
arr=np.array([1,2,3,4,5])
print(arr[2] + arr[4])

8


# Access 2-D Arrays

In [14]:
arr=np.array([[1,2,3,4],[7,3,4,5]])
print(f"second element of first row :{arr[0,1]} ")

second element of first row :2 


In [15]:
#Second row fifth element
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"second element of first row :{arr[1,4]} ")

second element of first row :10 


In [16]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [17]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -2])

Last element from 2nd dim:  9


# NumPy Array Slicing

In [18]:
myarr=np.array([1,2,3,4,5])
print(myarr[0:])

[1 2 3 4 5]


In [19]:
myarr=np.array([1,2,3,4,5])
print(myarr[:4])

[1 2 3 4]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [21]:
myarr=np.array([1,2,3,4,5])
print(myarr[0:5:2])

[1 3 5]


In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [23]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [25]:
arr=np.array([1,2,3,4,5])#copy ma upper part matra change huncha 
x=arr.copy()
arr[0]=4
print(arr)
print(x)

[4 2 3 4 5]
[1 2 3 4 5]


In [26]:
arr=np.array([1,2,3,4,5]) #VIEW VANEKO TALA MATHY DUITAI VALUE SAME AAUCHA
x=arr.view()
arr[0]=4
print(arr)
print(x)

[4 2 3 4 5]
[4 2 3 4 5]
